language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - iojs
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
before_script: ./bin/sassgraph descendents test/fixtures test/fixtures/simple/index.scss
after_success: npm run coverage
